<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Based on work from github.com/frou/GoFeather and github.com/DisposaBoy/GoSublime</string>
	<key>fileTypes</key>
	<array>
		<string>go</string>
	</array>
	<key>firstLineMatch</key>
	<string>-[*]-( Mode:)? Go -[*]-</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>GoSublime: Go</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.go</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\z</string>
			<key>name</key>
			<string>comment.line.double-slash.go</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.go</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.go</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.go</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.go</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.raw.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.gotemplate</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|nil|iota)\b</string>
			<key>name</key>
			<string>constant.language.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((\d+\.(\d+)?([eE][+-]?\d+)?|\d+[eE][+-]?\d+|\.\d+([eE][+-]?\d+)?)i?)\b</string>
			<key>name</key>
			<string>constant.numeric.floating-point.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+i|0[xX][0-9A-Fa-f]+|0[0-7]*|[1-9][0-9]*)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'(?:[^'\\]|\\(?:\\|[abfnrtv']|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3}))'</string>
			<key>name</key>
			<string>constant.other.rune.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bool|byte|complex(64|128)|error|float(32|64)|rune|string|u?int(8|16|32|64)?|uintptr)\b</string>
			<key>name</key>
			<string>storage.type.go</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A subset of keyword.other.go for flow control keywords.</string>
			<key>match</key>
			<string>\b(break|case|continue|default|defer|else|for|go|goto|if|range|return|select|switch)\b</string>
			<key>name</key>
			<string>keyword.control.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|case|chan|const|continue|default|defer|else|fallthrough|for|func|go|goto|if|import|interface|map|package|range|return|select|struct|switch|type|var)\b</string>
			<key>name</key>
			<string>keyword.other.go</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.go</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.initialize.go</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>This matches the 'x := 0' style of variable declaration.</string>
			<key>match</key>
			<string>(?:[[:alpha:]_][[:alnum:]_]*)(?:,\s+[[:alpha:]_][[:alnum:]_]*)*\s*(:=)</string>
			<key>name</key>
			<string>meta.initialization.short.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\Afunc|...\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\sfunc|....\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\Atype\s)\b(\w+)\b</string>
			<key>name</key>
			<string>entity.name.type.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\stype\s)\b(\w+)\b</string>
			<key>name</key>
			<string>entity.name.type.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append|cap|close|complex|copy|delete|imag|len|make|new|panic|print|println|real|recover)\b</string>
			<key>name</key>
			<string>support.function.builtin.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>support.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;-)</string>
			<key>name</key>
			<string>keyword.operator.channel.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;|&lt;=|&gt;|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&amp;&amp;|[|]{2}|!)</string>
			<key>name</key>
			<string>keyword.operator.logical.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([+]{2})</string>
			<key>name</key>
			<string>keyword.operator.increment.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(--)</string>
			<key>name</key>
			<string>keyword.decrement.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|(?:[+]|-|[|]|^|[*]|/|%|&lt;&lt;|&gt;&gt;|&amp;|&amp;^)=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([+]|-|[*]|/|%|&amp;|[|]|^|&amp;^|&lt;&lt;|&gt;&gt;)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;)</string>
			<key>name</key>
			<string>keyword.operator.semi-colon.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(,)</string>
			<key>name</key>
			<string>punctuation.definition.comma.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([.])</string>
			<key>name</key>
			<string>punctuation.definition.dot.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:)</string>
			<key>name</key>
			<string>punctuation.definition.colon.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\]|{|}|\(|\))</string>
			<key>name</key>
			<string>punctuation.definition.bracket.go</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abfnrtv'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3})</string>
					<key>name</key>
					<string>constant.character.escape.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.go</string>
				</dict>
			</array>
		</dict>
		<key>string_placeholder</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)%
                        (\d+\$)?                                    # field (argument #)
                        [#0\- +']*                                  # flags
                        [,;:_]?                                     # separator character (AltiVec)
                        ((-?\d+)|\*(-?\d+\$)?)?                     # minimum field width
                        (\.((-?\d+)|\*(-?\d+\$)?)?)?                # precision
                        [diouxXDOUeEfFgGaAcCsSqpnvtTbyYhHmMzZ%]     # conversion type
                    </string>
					<key>name</key>
					<string>constant.other.placeholder.go</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.go</string>
	<key>uuid</key>
	<string>1caaa75c-b61d-11e2-ba93-138feb5db969</string>
</dict>
</plist>
