<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gohtml</string>
	</array>
	<key>name</key>
	<string>GoSublime: HTML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.gotemplate</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.gohtml</string>
	<key>uuid</key>
	<string>78c486ec-0101-11e2-a85a-00262d996a67</string>
</dict>
</plist>
