---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct

  - package-ecosystem: gomod
    directory: /tools/mod # Not linked from /go.mod
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.5"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.6"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.7"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /tools/container-images/devcontainer
    schedule:
      interval: weekly
