#!/bin/sh -e

if [ ! -h src/github.com/coreos/etcd ]; then
	mkdir -p src/github.com/coreos/
	ln -s ../../.. src/github.com/coreos/etcd
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

go install github.com/coreos/etcd
go install github.com/coreos/etcd/bench
