FROM alpine:latest

RUN apk add --quiet --no-cache ca-certificates && \
  rm -rf /var/cache/*

ADD etcd /usr/local/bin/
ADD etcdctl /usr/local/bin/
RUN mkdir -p /var/etcd/
RUN mkdir -p /var/lib/etcd/

EXPOSE 2379 2380

# Define default command.
CMD ["/usr/local/bin/etcd"]
