FROM --platform=linux/riscv64 scratch

# TODO: use distroless once it supports riscv64
# https://github.com/GoogleContainerTools/distroless/issues/1269

ADD etcd /usr/local/bin/
ADD etcdctl /usr/local/bin/
ADD etcdutl /usr/local/bin/

WORKDIR /var/etcd/
WORKDIR /var/lib/etcd/

EXPOSE 2379 2380

# Define default command.
CMD ["/usr/local/bin/etcd"]
