FROM alpine:latest

ADD etcd /usr/local/bin/
ADD etcdctl /usr/local/bin/

ENV ETCD_DATA_DIR=/var/lib/etcd/
RUN mkdir -p $ETCD_DATA_DIR

EXPOSE 2379 2380

# Define default command.
CMD ["/usr/local/bin/etcd"]
