FROM golang:1.11.3 as builder
MAINTAINER "etcd Authors"

WORKDIR /tmp/go
COPY . /go/src/go.etcd.io/etcd
RUN CGO_ENABLED=0 go build -a -ldflags '-s' -v go.etcd.io/etcd/discoveryserver

FROM scratch
EXPOSE 8087
CMD [ "/discoveryserver" ]
COPY --from=builder /tmp/go/discoveryserver /discoveryserver
