#!/usr/bin/env bash

set -e

source ./build

export GOPATH=${PWD}/gopath
rm -rf $GOPATH/src
mkdir -p $GOPATH
ln -s ${PWD}/cmd/vendor $GOPATH/src

cd clientv3/integration
go test -v -race -cpu=2,4 -count=40 -run TestTxnWriteFail
cd -
