ARG GO_VERSION=1.24.3

FROM golang:$GO_VERSION AS build
RUN go install github.com/a8m/envsubst/cmd/envsubst@v1.4.3

ARG REF
COPY docker-compose.yml /docker-compose.yml.template
RUN REF=${REF} cat /docker-compose.yml.template | envsubst > /docker-compose.yml

FROM scratch
COPY --from=build /docker-compose.yml /docker-compose.yml
