---
name: Bug Report
description: Report a bug encountered while operating etcd
labels:
  - type/bug
body:
  - type: checkboxes
    id: confirmations
    attributes:
      label: Bug report criteria
      description: Please confirm this bug report meets the following criteria.
      options:
        - label: This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
        - label: This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
        - label: You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
        - label: Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

  - type: markdown
    attributes:
      value: |
        Please fill the form below and provide as much information as possible.
        Not doing so may result in your bug not being addressed in a timely manner.

  - type: textarea
    id: problem
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it (as minimally and precisely as possible)?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: textarea
    id: etcdVersion
    attributes:
      label: Etcd version (please run commands below)
      value: |
        <details>

        ```console
        $ etcd --version
        # paste output here

        $ etcdctl version
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Etcd configuration (command line flags or environment variables)
      value: |
        <details>

        # paste your configuration here

        </details>

  - type: textarea
    id: etcdDebugInformation
    attributes:
      label: Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)
      value: |
        <details>

        ```console
        $ etcdctl member list -w table
        # paste output here

        $ etcdctl --endpoints=<member list> endpoint status -w table
        # paste output here
        ```

        </details>

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
