---
name: Flaking Test
description: Report flaky tests
labels:
  - type/flake
  - area/testing
body:
  - type: textarea
    id: workflows
    attributes:
      label: Which Github Action / Prow Jobs are flaking?
    validations:
      required: true

  - type: textarea
    id: tests
    attributes:
      label: Which tests are flaking?
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Github Action / Prow Job link

  - type: textarea
    id: reason
    attributes:
      label: Reason for failure (if possible)

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?
