#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${DIR}
git clean -x -f dist

npm install
bower install
grunt build

export GOPATH="${DIR}/../../"

for i in `find dist -type f`; do
	file=$(echo $i | sed 's#dist/##g' | sed 's#/#-#g')
	go build github.com/jteeuwen/go-bindata
	./go-bindata -pkg "resources" -toc -out resources/$file.go -prefix dist $i
done
