apiVersion: v1
kind: Pod
metadata:
  labels:
    app: vulcand
  name: vulcand
spec:
  containers:
  - command:
    - /go/bin/vulcand
    - -apiInterface=0.0.0.0
    - --etcd=http://etcd-client:2379
    image: mailgun/vulcand:v0.8.0-beta.2
    name: vulcand
    ports:
    - containerPort: 8081
      name: api
      protocol: TCP
    - containerPort: 8082
      name: server
      protocol: TCP
  restartPolicy: Always
