// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: etcdserver.proto

package etcdserverpb

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	ID                   *uint64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Method               *string  `protobuf:"bytes,2,opt,name=Method" json:"Method,omitempty"`
	Path                 *string  `protobuf:"bytes,3,opt,name=Path" json:"Path,omitempty"`
	Val                  *string  `protobuf:"bytes,4,opt,name=Val" json:"Val,omitempty"`
	Dir                  *bool    `protobuf:"varint,5,opt,name=Dir" json:"Dir,omitempty"`
	PrevValue            *string  `protobuf:"bytes,6,opt,name=PrevValue" json:"PrevValue,omitempty"`
	PrevIndex            *uint64  `protobuf:"varint,7,opt,name=PrevIndex" json:"PrevIndex,omitempty"`
	PrevExist            *bool    `protobuf:"varint,8,opt,name=PrevExist" json:"PrevExist,omitempty"`
	Expiration           *int64   `protobuf:"varint,9,opt,name=Expiration" json:"Expiration,omitempty"`
	Wait                 *bool    `protobuf:"varint,10,opt,name=Wait" json:"Wait,omitempty"`
	Since                *uint64  `protobuf:"varint,11,opt,name=Since" json:"Since,omitempty"`
	Recursive            *bool    `protobuf:"varint,12,opt,name=Recursive" json:"Recursive,omitempty"`
	Sorted               *bool    `protobuf:"varint,13,opt,name=Sorted" json:"Sorted,omitempty"`
	Quorum               *bool    `protobuf:"varint,14,opt,name=Quorum" json:"Quorum,omitempty"`
	Time                 *int64   `protobuf:"varint,15,opt,name=Time" json:"Time,omitempty"`
	Stream               *bool    `protobuf:"varint,16,opt,name=Stream" json:"Stream,omitempty"`
	Refresh              *bool    `protobuf:"varint,17,opt,name=Refresh" json:"Refresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ffbeb3bebbce7e, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return m.Size()
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Request) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Request) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

func (m *Request) GetDir() bool {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return false
}

func (m *Request) GetPrevValue() string {
	if m != nil && m.PrevValue != nil {
		return *m.PrevValue
	}
	return ""
}

func (m *Request) GetPrevIndex() uint64 {
	if m != nil && m.PrevIndex != nil {
		return *m.PrevIndex
	}
	return 0
}

func (m *Request) GetPrevExist() bool {
	if m != nil && m.PrevExist != nil {
		return *m.PrevExist
	}
	return false
}

func (m *Request) GetExpiration() int64 {
	if m != nil && m.Expiration != nil {
		return *m.Expiration
	}
	return 0
}

func (m *Request) GetWait() bool {
	if m != nil && m.Wait != nil {
		return *m.Wait
	}
	return false
}

func (m *Request) GetSince() uint64 {
	if m != nil && m.Since != nil {
		return *m.Since
	}
	return 0
}

func (m *Request) GetRecursive() bool {
	if m != nil && m.Recursive != nil {
		return *m.Recursive
	}
	return false
}

func (m *Request) GetSorted() bool {
	if m != nil && m.Sorted != nil {
		return *m.Sorted
	}
	return false
}

func (m *Request) GetQuorum() bool {
	if m != nil && m.Quorum != nil {
		return *m.Quorum
	}
	return false
}

func (m *Request) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Request) GetStream() bool {
	if m != nil && m.Stream != nil {
		return *m.Stream
	}
	return false
}

func (m *Request) GetRefresh() bool {
	if m != nil && m.Refresh != nil {
		return *m.Refresh
	}
	return false
}

type Metadata struct {
	NodeID               *uint64  `protobuf:"varint,1,opt,name=NodeID" json:"NodeID,omitempty"`
	ClusterID            *uint64  `protobuf:"varint,2,opt,name=ClusterID" json:"ClusterID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_09ffbeb3bebbce7e, []int{1}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return m.Size()
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

func (m *Metadata) GetClusterID() uint64 {
	if m != nil && m.ClusterID != nil {
		return *m.ClusterID
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "etcdserverpb.Request")
	proto.RegisterType((*Metadata)(nil), "etcdserverpb.Metadata")
}

func init() { proto.RegisterFile("etcdserver.proto", fileDescriptor_09ffbeb3bebbce7e) }

var fileDescriptor_09ffbeb3bebbce7e = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0x3f, 0xcf, 0xd3, 0x30,
	0x10, 0xc6, 0x71, 0x93, 0xfe, 0x33, 0xa5, 0x14, 0x0b, 0xa1, 0x1b, 0x50, 0x14, 0x95, 0x25, 0x53,
	0x33, 0x20, 0x76, 0x04, 0xe9, 0x90, 0xa1, 0xa8, 0xa4, 0xa8, 0x48, 0x6c, 0xa6, 0x39, 0xa8, 0xa5,
	0xb6, 0x0e, 0x8e, 0x13, 0xf5, 0xa3, 0xb0, 0xf2, 0x6d, 0x18, 0xf9, 0x08, 0xa8, 0xef, 0x17, 0x79,
	0xe5, 0x4b, 0xda, 0x74, 0xca, 0xf3, 0xfc, 0x2e, 0xbe, 0x7b, 0xe4, 0x33, 0x9f, 0xa1, 0xdd, 0xe5,
	0x25, 0x9a, 0x1a, 0xcd, 0xa2, 0x30, 0xda, 0x6a, 0x31, 0xe9, 0x48, 0xf1, 0x7d, 0xfe, 0xc7, 0xe3,
	0xc3, 0x0c, 0x7f, 0x55, 0x58, 0x5a, 0x31, 0xe5, 0xbd, 0x34, 0x01, 0x16, 0xb2, 0xc8, 0xcf, 0x7a,
	0x69, 0x22, 0x5e, 0xf1, 0xc1, 0x0a, 0xed, 0x5e, 0xe7, 0xd0, 0x0b, 0x59, 0x34, 0xce, 0x5a, 0x27,
	0x04, 0xf7, 0xd7, 0xd2, 0xee, 0xc1, 0x23, 0x4a, 0x5a, 0xcc, 0xb8, 0xb7, 0x95, 0x07, 0xf0, 0x09,
	0x39, 0xe9, 0x48, 0xa2, 0x0c, 0xf4, 0x43, 0x16, 0x8d, 0x32, 0x27, 0xc5, 0x6b, 0x3e, 0x5e, 0x1b,
	0xac, 0xb7, 0xf2, 0x50, 0x21, 0x0c, 0xe8, 0xcf, 0x0e, 0x5c, 0xab, 0xe9, 0x29, 0xc7, 0x33, 0x0c,
	0x29, 0x44, 0x07, 0xae, 0xd5, 0xe5, 0x59, 0x95, 0x16, 0x46, 0xd4, 0xb3, 0x03, 0x22, 0xe0, 0x7c,
	0x79, 0x2e, 0x94, 0x91, 0x56, 0xe9, 0x13, 0x8c, 0x43, 0x16, 0x79, 0xd9, 0x1d, 0x71, 0x89, 0xbf,
	0x4a, 0x65, 0x81, 0xd3, 0x41, 0xd2, 0xe2, 0x25, 0xef, 0x6f, 0xd4, 0x69, 0x87, 0xf0, 0x94, 0x66,
	0x35, 0xc6, 0xcd, 0xc9, 0x70, 0x57, 0x99, 0x52, 0xd5, 0x08, 0x93, 0x66, 0xce, 0x0d, 0xb8, 0x1b,
	0xd9, 0x68, 0x63, 0x31, 0x87, 0x67, 0x54, 0x6a, 0x9d, 0xe3, 0x9f, 0x2b, 0x6d, 0xaa, 0x23, 0x4c,
	0x1b, 0xde, 0x38, 0x37, 0xf7, 0x8b, 0x3a, 0x22, 0x3c, 0xa7, 0x44, 0xa4, 0xa9, 0x87, 0x35, 0x28,
	0x8f, 0x30, 0x6b, 0x7b, 0x90, 0x13, 0xe0, 0x16, 0xf1, 0xc3, 0x60, 0xb9, 0x87, 0x17, 0x54, 0xb8,
	0xda, 0xf9, 0x7b, 0x3e, 0x5a, 0xa1, 0x95, 0xb9, 0xb4, 0xd2, 0x9d, 0xfe, 0xa4, 0x73, 0xbc, 0xed,
	0xa9, 0x75, 0x2e, 0xf7, 0xc7, 0x43, 0x55, 0x5a, 0x34, 0x69, 0x42, 0xeb, 0xf2, 0xb3, 0x0e, 0x7c,
	0x78, 0xf7, 0xf7, 0x12, 0xb0, 0x7f, 0x97, 0x80, 0xfd, 0xbf, 0x04, 0xec, 0xf7, 0x43, 0xf0, 0xe4,
	0xdb, 0x9b, 0x9f, 0x7a, 0xe1, 0x1e, 0xc2, 0x42, 0xe9, 0xd8, 0x7d, 0x63, 0x59, 0xa8, 0xb8, 0x7e,
	0x1b, 0xdf, 0x3f, 0x8e, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x24, 0x3f, 0xda, 0x3d, 0x02,
	0x00, 0x00,
}

func (m *Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Refresh != nil {
		i--
		if *m.Refresh {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.Stream != nil {
		i--
		if *m.Stream {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.Time != nil {
		i = encodeVarintEtcdserver(dAtA, i, uint64(*m.Time))
		i--
		dAtA[i] = 0x78
	}
	if m.Quorum != nil {
		i--
		if *m.Quorum {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.Sorted != nil {
		i--
		if *m.Sorted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.Recursive != nil {
		i--
		if *m.Recursive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.Since != nil {
		i = encodeVarintEtcdserver(dAtA, i, uint64(*m.Since))
		i--
		dAtA[i] = 0x58
	}
	if m.Wait != nil {
		i--
		if *m.Wait {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.Expiration != nil {
		i = encodeVarintEtcdserver(dAtA, i, uint64(*m.Expiration))
		i--
		dAtA[i] = 0x48
	}
	if m.PrevExist != nil {
		i--
		if *m.PrevExist {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.PrevIndex != nil {
		i = encodeVarintEtcdserver(dAtA, i, uint64(*m.PrevIndex))
		i--
		dAtA[i] = 0x38
	}
	if m.PrevValue != nil {
		i -= len(*m.PrevValue)
		copy(dAtA[i:], *m.PrevValue)
		i = encodeVarintEtcdserver(dAtA, i, uint64(len(*m.PrevValue)))
		i--
		dAtA[i] = 0x32
	}
	if m.Dir != nil {
		i--
		if *m.Dir {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Val != nil {
		i -= len(*m.Val)
		copy(dAtA[i:], *m.Val)
		i = encodeVarintEtcdserver(dAtA, i, uint64(len(*m.Val)))
		i--
		dAtA[i] = 0x22
	}
	if m.Path != nil {
		i -= len(*m.Path)
		copy(dAtA[i:], *m.Path)
		i = encodeVarintEtcdserver(dAtA, i, uint64(len(*m.Path)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Method != nil {
		i -= len(*m.Method)
		copy(dAtA[i:], *m.Method)
		i = encodeVarintEtcdserver(dAtA, i, uint64(len(*m.Method)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != nil {
		i = encodeVarintEtcdserver(dAtA, i, uint64(*m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Metadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ClusterID != nil {
		i = encodeVarintEtcdserver(dAtA, i, uint64(*m.ClusterID))
		i--
		dAtA[i] = 0x10
	}
	if m.NodeID != nil {
		i = encodeVarintEtcdserver(dAtA, i, uint64(*m.NodeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEtcdserver(dAtA []byte, offset int, v uint64) int {
	offset -= sovEtcdserver(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != nil {
		n += 1 + sovEtcdserver(uint64(*m.ID))
	}
	if m.Method != nil {
		l = len(*m.Method)
		n += 1 + l + sovEtcdserver(uint64(l))
	}
	if m.Path != nil {
		l = len(*m.Path)
		n += 1 + l + sovEtcdserver(uint64(l))
	}
	if m.Val != nil {
		l = len(*m.Val)
		n += 1 + l + sovEtcdserver(uint64(l))
	}
	if m.Dir != nil {
		n += 2
	}
	if m.PrevValue != nil {
		l = len(*m.PrevValue)
		n += 1 + l + sovEtcdserver(uint64(l))
	}
	if m.PrevIndex != nil {
		n += 1 + sovEtcdserver(uint64(*m.PrevIndex))
	}
	if m.PrevExist != nil {
		n += 2
	}
	if m.Expiration != nil {
		n += 1 + sovEtcdserver(uint64(*m.Expiration))
	}
	if m.Wait != nil {
		n += 2
	}
	if m.Since != nil {
		n += 1 + sovEtcdserver(uint64(*m.Since))
	}
	if m.Recursive != nil {
		n += 2
	}
	if m.Sorted != nil {
		n += 2
	}
	if m.Quorum != nil {
		n += 2
	}
	if m.Time != nil {
		n += 1 + sovEtcdserver(uint64(*m.Time))
	}
	if m.Stream != nil {
		n += 3
	}
	if m.Refresh != nil {
		n += 3
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Metadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NodeID != nil {
		n += 1 + sovEtcdserver(uint64(*m.NodeID))
	}
	if m.ClusterID != nil {
		n += 1 + sovEtcdserver(uint64(*m.ClusterID))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovEtcdserver(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEtcdserver(x uint64) (n int) {
	return sovEtcdserver(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEtcdserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ID = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEtcdserver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEtcdserver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Method = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEtcdserver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEtcdserver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Path = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Val", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEtcdserver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEtcdserver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Val = &s
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dir", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Dir = &b
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEtcdserver
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEtcdserver
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.PrevValue = &s
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevIndex", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PrevIndex = &v
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevExist", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.PrevExist = &b
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Expiration = &v
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wait", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Wait = &b
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Since", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Since = &v
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recursive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Recursive = &b
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sorted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Sorted = &b
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quorum", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Quorum = &b
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Time = &v
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stream", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Stream = &b
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refresh", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Refresh = &b
		default:
			iNdEx = preIndex
			skippy, err := skipEtcdserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEtcdserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Metadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEtcdserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NodeID = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ClusterID = &v
		default:
			iNdEx = preIndex
			skippy, err := skipEtcdserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEtcdserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEtcdserver(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEtcdserver
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEtcdserver
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEtcdserver
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEtcdserver
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEtcdserver
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEtcdserver        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEtcdserver          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEtcdserver = fmt.Errorf("proto: unexpected end of group")
)
