#!/bin/bash
SESSION=etcd-cluster

ulimit -n unlimited

tmux new-session -d -s $SESSION

# Setup a window for tailing log files
tmux new-window -t $SESSION:1 -n 'peers'
tmux split-window -h
tmux select-pane -t 0
tmux send-keys "../bin/etcd -peer-addr 127.0.0.1:7001 -addr 127.0.0.1:4001 -data-dir peer1 -name peer1" C-m

for i in 2 3; do
	tmux select-pane -t 0
	tmux split-window -v
	tmux send-keys "../bin/etcd -cors='*' -peer-addr 127.0.0.1:700${i} -addr 127.0.0.1:400${i} -peers 127.0.0.1:7001 -data-dir peer${i} -name peer${i}" C-m
done

# Attach to session
tmux attach-session -t $SESSION
