version: "2"
linters:
  default: none
  enable:
    - errorlint
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    nakedret:
      max-func-lines: 5
    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: early-return
          arguments:
            - preserveScope
        - name: error-return
        - name: error-naming
        - name: error-strings
        - name: errorf
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: superfluous-else
          arguments:
            - preserveScope
        - name: time-naming
        - name: unnecessary-stmt
        - name: use-any
        - name: var-declaration
        - name: var-naming
          arguments:
            - []
            - - GRPC
              - WAL
        - name: exported
          disabled: true
        - name: unexported-return
          disabled: true
    staticcheck:
      checks:
        - -SA1019
        - -SA2002
        - ST1019
        - all
    testifylint:
      enable-all: true
      formatter:
        require-f-funcs: true
    usetesting:
      os-mkdir-temp: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - ineffassign
        path: conversion\.go
      - linters:
          - staticcheck
        text: S1000
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - go.etcd.io
  exclusions:
    generated: lax
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
