---
name: Antithesis Verify

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'tests/antithesis/**'
      - '.github/workflows/antithesis-verify.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'tests/antithesis/**'
      - '.github/workflows/antithesis-verify.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build images
        run: |
          make -C tests/antithesis antithesis-build-etcd-image
          make -C tests/antithesis antithesis-build-client-docker-image

      - name: Set up Kubernetes cluster
        working-directory: ./tests/antithesis
        run: make antithesis-k8s-up

      - name: Run traffic
        working-directory: ./tests/antithesis
        run: make antithesis-run-k8s-traffic

      - name: Run validation
        working-directory: ./tests/antithesis
        run: make antithesis-run-k8s-validation

      - name: Clean up
        if: always()
        working-directory: ./tests/antithesis
        run: make antithesis-clean
