---
name: Test devcontainer
on:
  pull_request_target:
    paths:
      - '.devcontainer/devcontainer.json'
permissions: read-all
jobs:
  test-devcontainer:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/go:1.26-bookworm
    steps:
      - name: Build project using defined devcontainer
        run: |
          git clone --depth=1 --branch=${GITHUB_REF_NAME} https://github.com/${GITHUB_REPOSITORY} etcd
          cd etcd
          make build
