---
name: Reusable Robustness Workflow
on:
  workflow_call:
    inputs:
      etcdBranch:
        required: true
        type: string
      count:
        required: true
        type: number
      testTimeout:
        required: false
        type: string
        default: '30m'
      artifactName:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: "['ubuntu-latest']"
permissions: read-all

jobs:
  test:
    timeout-minutes: 210
    runs-on: ${{ fromJson(inputs.runs-on) }}
    container: golang:1.19-bullseye
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      # https://github.com/actions/checkout/issues/1169
      - run: git config --system --add safe.directory '*'
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: test-robustness
        env:
          ETCD_BRANCH: "${{ inputs.etcdBranch }}"
        run: |
          set -euo pipefail
          go clean -testcache

          # Use --failfast to avoid overriding report generated by failed test
          GO_TEST_FLAGS="-v --count ${{ inputs.count }} --timeout ${{ inputs.testTimeout }} --failfast --run TestRobustness"
          case "${ETCD_BRANCH}" in
            release-3.5)
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.5
              ;;
            release-3.4)
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.4
              ;;
            main)
              make gofail-enable
              make build
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness
              ;;
            *)
              echo "Failed to find target ${ETCD_BRANCH}"
              exit 1
              ;;
          esac
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        if: always()
        with:
          name: ${{ inputs.artifactName }}
          path: /tmp/results/*
